name: Code Coverage

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1

      - name: Build and Test
        run: xcodebuild test -project Sweat\ Social.xcodeproj -destination 'platform=iOS Simulator,name=iPhone 12,OS=14.3' build test

      - uses: codecov/codecov-action@v1.2.1
      
